### PR TITLE
Deep obd logo design

### PR DESCRIPTION
**Pull request by harunbadilli**

### CODE REVIEW

**Comment by uholeschak** [comment]
Hello,
i have check the file, the android images are very good in size and quality.
The AppIcon.ico is still a problem, you may try an online icon converter, the icon has to embed multiple sizes finally (at least 16, 32, 64, 128, 256 .ico and .png), it would be helpful if the background is transparent.
Could you also provide the original format of the program with which you have created the image? The .svg only contains the bitmaps no vector data.
For the android app store larger images will be needed, for this reason a scalable vector format required.

**Comment by harunbadilli** [comment]
I updated the PR. The original format and editable files can also be found here. https://drive.google.com/open?id=1Gojc9u4ZrU3XCZuRRp3_E4EbsXqQwkBL

**Comment by uholeschak** [comment]
Thanks very much, I will check the files soon.

**Comment by uholeschak** [comment]
Thanks, the icon seems to be ok, now I have to update the store

**Pull request closed without merging**
